export const CHAIN_ID_STABLE_MAINNET = 988;
export const CHAIN_ID_STABLE_TESTNET = 2201;
export const CHAIN_ID_ETH_MAINNET = 1;
export const CHAIN_ID_SEPOLIA = 11155111;

export const CHAIN_IDS = {
  STABLE_MAINNET: CHAIN_ID_STABLE_MAINNET,
  STABLE_TESTNET: CHAIN_ID_STABLE_TESTNET,
  ETH_MAINNET: CHAIN_ID_ETH_MAINNET,
  SEPOLIA: CHAIN_ID_SEPOLIA,
};
